#!/bin/bash

if [ "$#" -lt 1 ]
then
  echo -e "Usage: ./build [-e|--entity][-t|--threads][-d|--debug] name_of_project"
  echo -e "       ./build spotless"
  echo -e "       ./build clean name_of_project"
  exit 1
fi

# Setup Project Target
PROJECT_NAME="HelloWorld"
THREADS="-j1"
ENTITY_NAME=DBG
DEBUG=0
SILENT="-s"

if [ "$1" == "spotless" ]
then
	make spotless
	exit 0
elif [ "$1" == "clean" ]
then
	make clean PROJ=$2
	exit 0
fi

# some arguments don't have a corresponding value to go with it such
# as in the --default example).
# note: if this is set to -gt 0 the /etc/hosts part is not recognized ( may be a bug )
while [[ $# -gt 1 ]]
do
	key="$1"

	case $key in
		-e|--entity)
			ENTITY_NAME="$2"
			shift # past argument
		;;
		-t|--threads)
			THREADS="-j$2"
			shift # past argument
		;;
		-d|--debug)
			DEBUG=1
		;;
		-v|--verbose)
			SILENT=""
		;;
		*)
		        # unknown option
		;;
	esac
	shift # past argument or value
done

if [ ! -z "$1" ]
then
	PROJECT_NAME=$1
fi

echo "PROJECT_NAME=$PROJECT_NAME THREADS=$THREADS ENTITY_NAME=$ENTITY_NAME DEBUG=$DEBUG"

make $SILENT PROJ=$PROJECT_NAME ENTITY=$ENTITY_NAME $THREADS DEBUG=$DEBUG

