#!/bin/bash

function SystemExit()
{
    echo "Exiting Script" 1>&2
    exit 1
}

# Make sure only non-root users can run our script
if [[ $EUID -eq 0 ]]; then
   echo "SJSU-DEV-Linux installer script must NOT be run as root! " 1>&2
   exit 1
fi

# Check if git exists
# if ! which git > /dev/null; then
# 	echo " ───────────────────────────────────────────────────┐"
# 	echo "         GIT NOT FOUND: Please install GIT           "
# 	echo "└─────────────────────────────────────────────────── "
# 	SystemExit
# fi

echo " ──────────────────────────────────────────────────┐"
echo "            Acquiring sudo privileges               "
echo "└────────────────────────────────────────────────── "
sudo echo "" || SystemExit

# Stash the tool directory
TOOLDIR=$(dirname "$0")/tools

echo " ──────────────────────────────────────────────────┐"
echo "  Starting SJSU-DEV-Linux Environment Setup Script  "
echo "└────────────────────────────────────────────────── "
sleep 1

echo " ──────────────────────────────────────────────────┐"
echo "              Detecting your platform               "
echo "└────────────────────────────────────────────────── "
ARCH=$(uname -m)
SYS=$(uname -s)
#SYSREL=$(uname -r) # Probably don't need this, but maybe
if [[ "$ARCH" != 'x86_64' || "$ARCH" == "amd64" ]]; then
	echo 'Your system is not supported! Only 64-bit Linux and OSX systems are supported.'
	SystemExit
fi

echo " ──────────────────────────────────────────────────┐"
echo "           Installing gcc-arm-embedded              "
echo "└────────────────────────────────────────────────── "

# Enter Tools directory
cd $TOOLDIR
if [ "$SYSREL" == "Darwin" ]; then
	curl -LO https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-mac.tar.bz2
	GCC_PKG=gcc-arm-none-eabi-6-2017-q2-update-mac.tar.bz2
	SJSUONEDEV=/dev/tty.usbserial-A503JOLS
else
	curl -LO https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2
	GCC_PKG=gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2
	SJSUONEDEV=/dev/ttyUSB0
fi
tar xvjf $GCC_PKG
cd ..
# Exited Tools Directory

if which getent > /dev/null; then
	THE_GROUP=$(getent group | grep 'dial' | cut -d: -f1)
	echo " ──────────────────────────────────────────────────┐"
	echo "      Adding current user to '$GROUP' group"
	echo "└────────────────────────────────────────────────── "
	sudo adduser $USER $THE_GROUP
fi

if which apt > /dev/null; then
	echo " ───────────────────────────────────────────────────┐"
	echo "                Installing OpenOCD                   "
	echo "└─────────────────────────────────────────────────── "
	sudo apt -y install openocd
fi

echo " ───────────────────────────────────────────────────┐"
echo "       Installing 'PIP' Python package installer     "
echo "└─────────────────────────────────────────────────── "
sudo -H pip install --upgrade pip
sudo -H pip install --upgrade virtualenv

echo " ───────────────────────────────────────────────────┐"
echo "                 Installing GDBGUI                   "
echo "└─────────────────────────────────────────────────── "
sudo -H pip install --upgrade gdbgui

echo " ───────────────────────────────────────────────────┐"
echo "                Installing Hyperload                 "
echo "└─────────────────────────────────────────────────── "
git clone --depth=1 https://github.com/kammce/Hyperload.git $TOOLDIR/Hyperload/
$TOOLDIR/Hyperload/setup

echo " ───────────────────────────────────────────────────┐"
echo "                Installing Telemetry                 "
echo "└─────────────────────────────────────────────────── "
git clone --depth=1 https://github.com/kammce/Telemetry.git $TOOLDIR/Telemetry
$TOOLDIR/Telemetry/setup

echo > env.sh <<END
#!/bin/bash
# Setup a base directory:
BASE=`dirname $TOOLDIR/../`

# SJSUOne Board Settings:
SJSUONEDEV="$SJSUONEDEV" # Set this to your board ID
SJSUONEBAUD=38400

# Project Target Settings:
# Sets the binary name, defaults to "firmware" (Optional)
PROJ=firmware
# Sets which DBC to generate, defaults to "DBG"
ENTITY=DBG

# Compiler and library settings:
# Selects compiler version to use
CC=gcc-arm-none-eabi-6-2017-q2-update
PATH=\$PATH:$BASE/tools/\$CC/bin:$BASE/tools/Hyperload/:$BASE/tools/Telemetry/
LIB_DIR="$BASE/lib"

# Make system settings:
# Number of jobs = 8
# Tune this to nthreads (f.eks. my system has a quad core with two threads per core = 8 threads)
MAKEFLAGS=" -j 8"

# Export everything to the environment
export PATH
export PROJ
export ENTITY
export LIB_DIR
export SJSUONEDEV
export SJSUONEBAUD
export MAKEFLAGS
END

echo
echo " ──────────────────────────────────────────────────────────────┐"
echo "                      Setup complete!                           "
echo "                                                                "
echo "  PLEASE LOGOUT AND BACK IN to load code into your SJOne Board  "
echo "└────────────────────────────────────────────────────────────── "
echo
