#!/bin/bash
# Find the directory that contains the physical script file
if readlink "$0" > /dev/null; then
	REALDIR=$(readlink "$0" | xargs dirname)
else
	REALDIR=$(dirname "$0")
fi

# Activate the python virtual environment
source $REALDIR/modules/bin/activate

# Start hyperload using the virtualenv then send in the args
$REALDIR/modules/bin/python $REALDIR/hyperload.py $@
