#!/bin/bash

# Remove modules (virtual environment folder)
rm -rf modules
# Initialize modules folder as a "virtual environment"
virtualenv modules
# Activate virtual environment
source modules/bin/activate
# Install all requirements within requirements.txt file
pip install -r ./requirements.txt
# Deactivate virtual environment
deactivate
